### PR TITLE
Added functionality to have child form groups

### PR DESCRIPTION
**Pull request by harish282**
I was facing a problem to have multiple dynamically children of parent form group. I found current code was not dealing with it so made changes my self. Have a look and if you feel good enough then you can merge.

### CODE REVIEW

**Comment by sabrio** [comment]
@harish282 great to see you here and I am so exciting to bring this feature&work in. I have planing for so long to have this feature but I just don't have the time. Give me sometime to review the code, see what can we improve and merge this thing.
Keep the good work up.

**Comment by sabrio** [comment]
@harish282 I did some changes, can you please check them and provide me feedback. If everything is alright, we'll need to update docs, do some refactoring and then merge. 
Best regards.

**Comment by harish282** [comment]
@sabrio Thanks for incorporated the changes. I only have one suggestion, please change removeChild to removeChildGroup to have a consistency. waiting for the merger so that i may update my project to use updated library.

**Comment by sabrio** [comment]
@harish282 no problem, I will change it and I'll try to do some refactoring, can you please update the docs and the demo, in order to have this well documented?

**Pull request merged**
